server:
  port: ${PROD_SERVER_PORT:8080}

api:
  version: ${PROD_API_VERSION}

frontend:
  url: ${PROD_FRONTEND_URL}

jwt:
  secret: ${PROD_JWT_SECRET}
  expiration: 86400000


nats:
  url: ${PROD_NATS_URL}
  username: ${PROD_NATS_USERNAME}
  password: ${PROD_NATS_PASSWORD}



spring:
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
      ignored-interfaces:
        - docker0
        - veth.*
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST


eureka:
  client:
    service-url:
      defaultZone: ${PROD_EUREKA_URL:http://discovery-server-prod:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${EUREKA_HOSTNAME:api-gateway-prod}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,refresh
  endpoint:
    health:
      show-details: always
  level:
    root: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG