server:
  port: ${PROD_SERVER_PORT:8080}

api:
  version: ${PROD_API_VERSION}

frontend:
  url: ${PROD_FRONTEND_URL}

jwt:
  secret: ${PROD_JWT_SECRET}
  expiration: 86400000


nats:
  url: ${PROD_NATS_URL}
  username: ${PROD_NATS_USERNAME}
  password: ${PROD_NATS_PASSWORD}



spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

eureka:
  client:
    service-url:
      defaultZone: ${PROD_EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true

eureka:
  client:
    service-url:
      defaultZone: ${PROD_EUREKA_URL:http://discovery-server-prod:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    root: INFO
    "[com.netflix.eureka]": INFO
    "[com.netflix.discovery]": INFO

