server:
  port: ${SERVER_PORT:8080}

api:
  version: /api/v1

spring:
  data:
    redis:
      host: ${DEV_REDIS_HOST:localhost}
      port: ${DEV_REDIS_PORT:6379}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${DEV_EUREKA_URL:http://127.0.0.1:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5

nats:
  url: ${DEV_NATS_URL:nats://localhost:4222}
  username: ${DEV_NATS_USERNAME:auth-server}
  password: ${DEV_NATS_PASSWORD:auth-secret}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: refresh

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}
