server:
  port: ${SERVER_PORT:8080}

api:
  version: /api/v1

spring:
  data:
    redis:
      host: ${PROD_REDIS_HOST:redis-server}
      port: ${PROD_REDIS_PORT:6379}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

eureka:
  client:
    service-url:
      defaultZone: ${PROD_EUREKA_URL:https://discovery-server-latest-6p1n.onrender.com/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true

nats:
  url: ${PROD_NATS_URL}
  username: ${PROD_NATS_USERNAME}
  password: ${PROD_NATS_PASSWORD}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: refresh

frontend:
  url: ${FRONTEND_URL}
